### ISSUE TITLE
ionic native contact 

### ISSUE THREAD

**Issue by 1AbhinavMaurya** [janpio/ionic-native-contacts#4]
![capture](https://user-images.githubusercontent.com/46446506/52551939-7fc6e980-2e04-11e9-8d2c-23e84f11cf1b.PNG)
in this pic while click on the search button allows contact in my simulator.
![capture1](https://user-images.githubusercontent.com/46446506/52551984-ae44c480-2e04-11e9-8fbb-4ef8a6320a42.PNG)
in this pic list is a show but photos not loaded.
![capture2](https://user-images.githubusercontent.com/46446506/52552020-c3b9ee80-2e04-11e9-9616-1cf3ad13cebc.PNG)
in this pic, while clicking again on search button this will re-add contacts again

**Comment by janpio** [comment]
So? What does this have to do with this repository? You did implement the search yourself, didn't you?

About the broken images: https://ionic.zone/debug/remote-debug-your-app

**Comment by 1AbhinavMaurya** [comment]
thanks, bro issue is resolved. can u help this one also I am implemented facebook login fetch data from Facebook API but while I send it our backend it shows error on pic 2 (capture2)
![capture1](https://user-images.githubusercontent.com/46446506/52709087-cad22f80-2fb1-11e9-9d4d-458c131cee68.PNG)
![capture2](https://user-images.githubusercontent.com/46446506/52709105-d160a700-2fb1-11e9-8942-13c70df7b08d.PNG)

**Comment by janpio** [comment]
No. Create a topic at https://forum.ionicframework.com/ please.
