### ISSUE TITLE
getting contact details null

### ISSUE THREAD

**Issue by AbhijeetFarakate** [janpio/ionic-native-contacts#5]
I am not getting any contacts details

`import { Contacts } from '@ionic-native/contacts/ngx';`

`constructor(private contactsPlugin: Contacts) {}`

`this.contactsPlugin.find(["displayName", "phoneNumbers","photos"], {multiple: true, hasPhoneNumber: true})`
`.then((contacts) => {`
`console.log("Length: ", contacts.length);`
        `for(let i=0; i < contacts.length; i++){`
`          console.log('... ',contacts[i]);`
`          if ( contaxts[i].displayName != null ) {`
`            console.log("--> ", contacts[i].displayName );`
`          }`
`        }`
`      }, `
`      (error) => {`
`        console.error("Contacts plugin: ", error)`
`      })`

I am using,
"@ionic-native/contacts": "^5.0.0"
"cordova-plugin-contacts": "3.0.1"

**Comment by janpio** [comment]
This repository is not using Ionic Native 5 and not the /ngx version. You should probably ask this in the Ionic forum or the real Ionic Native repository.
